name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout repository
      - uses: actions/checkout@v2
          with:
            fetch-depth: 0

      - name: Codecov
        coverage:
          status:
            patch:
              default:
                target: 100%
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
