name: code_analyzers
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_analyzers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
         bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --config .rubocop.yml
